config/routes.rb
Rails.application.routes.draw do
  get 'tags/create'

  get 'bloggr/index'

  root 'bloggr#index'
  
  resources :posts

  resources :users do 
    resources :posts
  end
  resources :tags do
    resources :posts
  end 
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  
  get '/signup' => 'users#new'
  post '/users' => 'users#create'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :post_tags
  has_many :tags, through: :post_tags
end

app/models/post_tag.rb
class PostTag < ActiveRecord::Base
	belongs_to :post
	belongs_to :tag
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :post_tags
  has_many :posts, through: :post_tags
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end
end

app/controllers/bloggr_controller.rb
class BloggrController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_filter :authorize
 
  def index
    # @tags = Tag.new()
  	@posts = Post.all
  end
  def new
  	@tags = Tag.all
  end
  def create
  	post = Post.new(post_params)
  	tags = Tag.where(:id => params[:tag_ids])
  	tags.each do |t|
  		post.tags << t
  	end
  	
  	post.user_id = current_user.id
    if post.save
      redirect_to posts_path
    else
      redirect_to '/signup'
    end
  end
  private
  def post_params
    params.require(:post).permit(:title, :content,{:tag_ids => []})
  end
  # def tag_params
  #   params.require(:tag).permit(:name, :id)
  # end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.find_by_email(params[:email])
    # If the user exists AND the password entered is correct.
    if user && user.authenticate(params[:password])
      # Save the user id inside the browser cookie. This is how we keep the user
      # logged in when they navigate around our website.
      session[:user_id] = user.id
      redirect_to '/'
    else
      # If user's login doesn't work, send them back to the login form.
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_filter :authorize
  def index
  end
  def show
  	@tag = Tag.find(params[:id])
  	@posts = @tag.posts
  end
  def new
  end
  def create
  	@tag = Tag.new(tag_params)
  	@tag.save
  	redirect_to new_user_post_path(current_user)
  end
  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  end
  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to '/'
    else
      redirect_to '/signup'
    end
  end

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bloggr_helper.rb
module BloggrHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bloggr/index.html.erb
<h1>Welcome to Bloggr</h1>
<p></p>
<%=link_to 'My Blog', posts_path  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bloggr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if current_user %>
  Signed in as <%= current_user.username %> | <%= link_to "Logout", '/logout' %>
<% else %>
  <%= link_to 'Login', '/login' %> | <%= link_to 'Signup', '/signup' %>
<% end %>

<%= yield %>

</body>
</html>

app/views/posts/index.html.erb
<h2> All Posts </h2>

 <%=link_to 'New User', new_user_path %>

<%=link_to 'New Post', new_user_post_path(current_user) %><br><br>

<% @posts.each do |post| %>
	Title: <%=post.title %><br>
	Content:
	<%= post.content %><br>
	Author: <%=post.user.username if post.user  %><br>
	Tags : 
		<%post.tags.each do |t|%>
			<%= link_to t.name, tag_path(t) %>,
		<% end %><br><br>
<% end %>

<%=link_to 'Back', controller: 'bloggr'  %>

app/views/posts/new.html.erb
<h2>New Post Form</h2>

<%= form_for :post, url: user_posts_path  do |f| %>
		<p>
			<%= f.label :title %><br>
			<%= f.text_field :title %>
		</p>

		<p>
			<%= f.label :content %><br>
			<%= f.text_area :content %>
		</p>
			<% @tags.each do |tag| %>
		    
 			<%=check_box_tag 'tag_ids[]', tag.id -%>
	    	<%= h tag.name%>

		  <% end %>
			
		<p>
			<%=f.submit%>
		</p>
<% end %>

<h2>New Tag</h2>
<%=form_for :tag, url: tags_path do |f| %>
	<p>
		<%= f.label :name %><br>
		<%= f.text_field :name %>
	</p>
	<p>
		<%=f.submit%>
	</p>
<% end %>

app/views/tags/create.html.erb
<h1>Tags</h1>
<p></p>

app/views/tags/index.html.erb
index.html.erb

app/views/tags/new.html.erb
new.html.erb

app/views/tags/show.html.erb
<h2> All Posts with Tag <%=@tag.name  %> </h2>

<% @posts.each do |post| %>
	Title: <%=post.title %><br>
	Content:
	<%= post.content %><br>
	Author: <%=post.user.username if post.user  %><br>
	Tags : 
		<%post.tags.each do |t|%>
			<%= link_to t.name, tag_path(t) %>,
		<% end %><br><br>
<% end %>

<%=link_to 'Back', controller: 'bloggr'  %>

app/views/users/new.html.erb
<h1>Signup!</h1>

<%= form_for :user, url: '/users' do |f| %>

  Name: <%= f.text_field :username %>
  Email: <%= f.text_field :email %>
  Password: <%= f.password_field :password %>
  Password Confirmation: <%= f.password_field :password_confirmation %>
  <%= f.submit "Submit" %>

<% end %>